- name: Make sure Python deps are installed
  apt:
    name: python3-psycopg2

- name: Ensure PostgreSQL users are present.
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: Ensure PostgreSQL databases are present.
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: true
  become_user: postgres
